# .woodpecker.yml
pipeline:
  build-and-push-image:
    image: plugins/docker
    settings:
      # Use Codeberg's container registry
      registry: codeberg.orgq
      # Codeberg CI automatically provides these credentials
      username: ${CI_REGISTRY_USER}
      password: ${CI_REGISTRY_PASSWORD}
      # The final image name will be: codeberg.org/YourUsername/your-repo:latest
      repo: ${CI_REGISTRY}/${CI_REPO}
      tags: latest
    when:
      branch: main

  deploy-to-railway:
    image: railway/cli:latest
    # You must create a 'RAILWAY_TOKEN' secret in your Codeberg repo settings
    secrets: [ RAILWAY_TOKEN ]
    commands:
      # Login to Railway CLI
      - railway login --token ${RAILWAY_TOKEN}
      # Trigger a deployment. Railway will automatically detect the Dockerfile.
      # Ensure your project is linked to your Codeberg repo on Railway's dashboard first.
      - railway up --detach
    depends_on:
      - build-and-push-image
    when:
      branch: main