when:
  branch: main
  event: push

steps:
  # STEP 1: RUN TESTS
  test:
    image: docker.io/library/golang:1.25.0
    commands:
      - echo "🧪 Running Go application tests using Go 1.25.0..."
      - go mod tidy
      - go test -v ./...

  # STEP 2: DEPLOY TO RENDER
  deploy:
    image: docker.io/curlimages/curl
    environment:
      RENDER_DEPLOY_HOOK:
        from_secret: RENDER_DEPLOY_HOOK
    commands:
      - echo "✅ All tests passed successfully."
      - echo "🚀 Triggering a new deployment on Render..."
      - curl -X POST "$RENDER_DEPLOY_HOOK"
    # 'when' block-ah innum theliva ezhuthi irukom.
    when:
      - status: [ success ]