# .woodpecker.yml

name: Test and Deploy to Render
on:
  push:
    branches:
      - main # Intha pipeline 'main' branch-la push panna mattum run aagum.

steps:
  # STEP 1: TEST THE CODE
  # Unga code-la irukura tests-ah run pannum.
  # Ithu fail aana, pipeline ingaye nindrum, deploy aagathu.
  test:
    image: docker.io/library/golang:1.21
    commands:
      - echo "🧪 Running Go tests..."
      - go mod tidy
      - go test -v ./...

  # STEP 2: DEPLOY TO RENDER
  # Muthal step ('test') pass aana mattum than intha step run aagum.
  deploy:
    image: docker.io/curlimages/curl
    secrets: [ RENDER_DEPLOY_HOOK ] # Codeberg secret-ah inga use panrom.
    commands:
      - echo "✅ Tests passed!"
      - echo "🚀 Triggering a new deployment on Render..."
      - curl -X POST "$RENDER_DEPLOY_HOOK" # Render-oda deploy hook-ah call pannuthu.
    when:
      status:
        - success # Previous steps success aana mattum than ithu nadakum.